### ISSUE TITLE
win10 install

### ISSUE THREAD

**Issue by ghost** [safeminex/safeminex#5]
Hi!

under win10 it stops with the following error message :
![safex](https://user-images.githubusercontent.com/108800590/194847192-ac20a438-d4cc-4b21-bb82-bdf90a55a69b.JPG)

**Comment by safeminex** [comment]
hi
please check your MingGW app.

and reinstall smx qt.

i am use win10 and win 11. no issue

thanks

**Comment by safeminex** [comment]
done
